name: App

on:
  workflow_dispatch:

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: try to commit and push something
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config user.name 'Timestamper'
          git config user.email 'timestamper@gr-oss.io'
          date=$(date)
          echo $date > date.txt
          git add date.txt
          git commit -m "Update date to $date"
          git push
