name: App

on:
  workflow_dispatch:

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
        with:
          script: |
            const octokit = require('octokit')
            
            const app = new octokit.App({
              appId: process.env.APP_ID,
              privateKey: process.env.APP_PRIVATE_KEY,
            })
