name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: cuda-${{ github.run_id }}
    steps:
      - name: Display context
        run: |
          cat << EOF
          ${{ toJSON(github) }}
          EOF
