name: CI

on:
  push:
  pull_request:

jobs:
  build:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Display context
        run: |
          cat << EOF
          ${{ toJSON(github) }}
          EOF
