name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Display context
        run: |
          cat << EOF
          ${{ toJSON(github) }}
          EOF
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test
          path: ${{ env.VCPKG_INSTALLATION_ROOT }}/bootstrap-vcpkg.sh
