name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display context
        run: |
          cat << EOF
          ${{ toJSON(github) }}
          EOF

  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call workflow
        run: gh workflow run check-empty.yml --repo ${{ github.repository }} --ref main -f condition=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
