name: CI

on:
  push:
  pull_request:

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job a"

  b:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job b"

  c:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job c" && exit 1

  all-required-checks-complete:
    needs: [a, b, c]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Display needs context
        run: |
          cat << EOF
          ${{ toJSON(needs) }}
          EOF
