name: Dev

on:
  workflow_dispatch:
    inputs:
      os:
        description: Runner operating system
        required: true
        default: 'ubuntu-latest'

jobs:
  dev:
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - name: Start CentOS container
        run: docker run -d --name centos --entrypoint tail -v $PWD:$PWD -w $PWD centos:7 -f /dev/null
      - name: Install cmake in container
        run: |
          docker exec centos yum install -y centos-release-scl epel-release
          docker exec yum install -y devtoolset-7 rh-git227 openssl-devel flex bison cmake3
          docker exec ln -s cmake3 /usr/bin/cmake
      - name: connect with upterm
        uses: lhotari/action-upterm@v1
        with:
          limit-access-to-users: jgiannuzzi
        env:
          GITHUB_TOKEN_TEMP: ${{ secrets.GITHUB_TOKEN }}
