name: Dev

on:
  workflow_dispatch:
    inputs:
      os:
        description: Runner operating system
        required: true
        default: 'ubuntu-latest'

jobs:
  dev:
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
