name: Dev

on:
  workflow_dispatch:
    inputs:
      os:
        description: Runner operating system
        required: true
        default: 'ubuntu-latest'

jobs:
  dev:
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: connect with upterm
        uses: lhotari/action-upterm@v1
        with:
          limit-access-to-users: jgiannuzzi
        env:
          GITHUB_TOKEN_TEMP: ${{ secrets.GITHUB_TOKEN }}
