name: Dev

on:
  workflow_dispatch:
    inputs:
      os:
        description: Runner operating system
        required: true
        default: 'ubuntu-latest'

jobs:
  dev:
    container: centos:7
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - name: Install prerequisites
        run: yum install -y sudo
      - name: connect with upterm
        uses: lhotari/action-upterm@v1
        with:
          limit-access-to-users: jgiannuzzi
        env:
          GITHUB_TOKEN_TEMP: ${{ secrets.GITHUB_TOKEN }}
