name: Secret

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Display context
        run: |
          cat << EOF
          ${{ toJSON(github) }}
          EOF
      - name: Use secret
        run: base64 <<< "${{ secrets.SUPER_SECRET }}"
